# Base configs
baseurl: "https://gabbyarzola.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "G-SPX5LPS80H"

# UI configs
title: "Gabby Arzola"
subtitle: "I take Photographs"
author: "Gabby Arzola"
header:
 title: "Photos"
 subtitle: "by Gabby Arzola"
footer:
 name: "Hello"
 bio: "Pictures taken with Canon EOS 6D and Fujifilm x-t4. This site is for personal use."
 github: ""
web_design: "Gabby Arzola"
social_urls:
